version: '3'

includes: 
  backend: 
    taskfile: ./backend/Taskfile.yml
    dir: ./backend

tasks:
  setup-backend-dev-env:
    desc: copies the .env file and setups the backend dev tools (all necessary tools need to be installed)
    cmds:
      - task: backend:setup-dev-env

  deploy-backend-service:
    desc: deploys the backend
    cmds: 
      - task: backend:deploy-service

  default:
    cmds:
      - task: setup-backend-dev-env
