version: '3'

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=Universe
      - POSTGRES_PASSWORD=Stardust
      - POSTGRES_DB=openfh

  cache:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
