version: '3'

services:
  database:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  cache:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${REDIS_PW}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
